### ISSUE TITLE
Indexing errors stacktrace is written in catalina.out instead of taxonoverflow.log

### ISSUE THREAD

**Issue by aruizca** [AtlasOfLivingAustralia/taxon-overflow#99]
This stacktrace was found on catalina.out instead of taxonoverflow.log

```
java.lang.RuntimeException: org.codehaus.groovy.grails.web.converters.exceptions.ConverterException: org.springframework.web.client.RestClientException: Failed to get json from web service (http://ecodata-sightings.ala.org.au/record/510d9d453dff95cd9ba73e96). class java.io.FileNotFoundException http://ecodata-sightings.ala.org.au/record/510d9d453dff95cd9ba73e96, java.io.FileNotFoundException: http://ecodata-sightings.ala.org.au/record/510d9d453dff95cd9ba73e96
    at org.codehaus.groovy.grails.web.converters.AbstractConverter.toString(AbstractConverter.java:111)
    at org.codehaus.groovy.runtime.typehandling.ShortTypeHandling.castToString(ShortTypeHandling.java:42)
    at au.org.ala.taxonoverflow.ElasticSearchService.indexQuestion(ElasticSearchService.groovy:128)
    at au.org.ala.taxonoverflow.ElasticSearchService$indexQuestion$12.callCurrent(Unknown Source)
    at au.org.ala.taxonoverflow.ElasticSearchService.processIndexTaskQueue(ElasticSearchService.groovy:202)
    at au.org.ala.taxonoverflow.ElasticSearchService.processIndexTaskQueue(ElasticSearchService.groovy)
    at au.org.ala.taxonoverflow.ElasticSearchService$$FastClassBySpringCGLIB$$b82326b6.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:708)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:98)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:262)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:95)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:644)
    at au.org.ala.taxonoverflow.ElasticSearchService$$EnhancerBySpringCGLIB$$ed8c0e9.processIndexTaskQueue(<generated>)
    at au.org.ala.taxonoverflow.ElasticSearchService$processIndexTaskQueue$1.call(Unknown Source)
    at au.org.ala.ProcessIndexingQueueJob.execute(ProcessIndexingQueueJob.groovy:13)
    at sun.reflect.GeneratedMethodAccessor277.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at grails.plugins.quartz.GrailsJobFactory$GrailsJob.execute(GrailsJobFactory.java:104)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.codehaus.groovy.grails.web.converters.exceptions.ConverterException: org.springframework.web.client.RestClientException: Failed to get json from web service (http://ecodata-sightings.ala.org.au/record/510d9d453dff95cd9ba73e96). class java.io.FileNotFoundException http://ecodata-sightings.ala.org.au/record/510d9d453dff95cd9ba73e96, java.io.FileNotFoundException: http://ecodata-sightings.ala.org.au/record/510d9d453dff95cd9ba73e96
    at org.codehaus.groovy.grails.web.converters.marshaller.ClosureObjectMarshaller.marshalObject(ClosureObjectMarshaller.java:65)
    at grails.converters.JSON.value(JSON.java:202)
    at grails.converters.JSON.render(JSON.java:134)
    at org.codehaus.groovy.grails.web.converters.AbstractConverter.toString(AbstractConverter.java:109)
    ... 23 more
Caused by: org.springframework.web.client.RestClientException: Failed to get json from web service (http://ecodata-sightings.ala.org.au/record/510d9d453dff95cd9ba73e96). class java.io.FileNotFoundException http://ecodata-sightings.ala.org.au/record/510d9d453dff95cd9ba73e96, java.io.FileNotFoundException: http://ecodata-sightings.ala.org.au/record/510d9d453dff95cd9ba73e96
    at sun.reflect.GeneratedConstructorAccessor200.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
    at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:71)
    at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:81)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190)
    at au.org.ala.taxonoverflow.AbstractWebService.getJson(AbstractWebService.groovy:20)
    at sun.reflect.GeneratedMethodAccessor626.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
    at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1460)
    at groovy.lang.ExpandoMetaClass.invokeStaticMethod(ExpandoMetaClass.java:1133)
    at org.codehaus.groovy.runtime.callsite.StaticMetaClassSite.callStatic(StaticMetaClassSite.java:62)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:165)
    at au.org.ala.taxonoverflow.EcodataService.$tt__getRecord(EcodataService.groovy:29)
    at au.org.ala.taxonoverflow.EcodataService$_getRecord_closure2.doCall(EcodataService.groovy)
    at sun.reflect.GeneratedMethodAccessor620.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1206)
    at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1120)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
    at groovy.lang.Closure.call(Closure.java:423)
    at groovy.lang.Closure.call(Closure.java:439)
    at org.codehaus.groovy.grails.orm.support.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:90)
    at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
    at org.codehaus.groovy.grails.orm.support.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:87)
    at au.org.ala.taxonoverflow.EcodataService.getRecord(EcodataService.groovy)
```

**Comment by aruizca** [comment]
We need to check the log4j configuration which is probably staffed up
